language: node_js
node_js:
  - "7.4.0"
script:
  - npm run build
after_success:
  - surge --project ./build/ --domain art.edwardessing.com
before_install:
  - npm install imagemagick
  - PKG_CONFIG_PATH=/opt/ImageMagick/lib/pkgconfig npm install --save imagemagick-native