language: node_js
node_js:
  - "7.4.0"
script:
  - npm run build
after_success:
  - surge --project ./build/ --domain art.edwardessing.com
before_install:
  - apt-get install -y imagemagick libmagick++-dev pkg-config
  - PKG_CONFIG_PATH=/usr/bin/pkg-config npm install --save imagemagick-native