# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edward essing - art
email: edwardessing@gmail.com
description: 'edward essing - art'
baseurl: ''
url: 'edwardessing' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Server Config options
livereload: true     # You no longer need to include --livereload:
                     # jekyll serve -L
reload_port: 5678    # If you don't want to use the default port

# Sass
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      categories: ''
      tags: []
      featured-image: ''
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      featured-image: ''
  - scope:
      path: ''
      type: galleries
    values:
      layout: gallery
      tags: []
      featured-image: ''
      homepage-thumbnail: ''
  - scope:
      path: "assets/img"
    values:
      image: true

# Collections
collections:
  galleries:
    output: true
    permalink: /:collection/:path/

autopages:
  enabled: false

permalink: pretty

exclude: [README.md, bower.json]

# Assets settings
assets:
  source_maps: true
  digest: true
  compress:
    css: false
    js: false
  sources:
    - assets
    - assets/selected

# Picture tag
picture:
  source: "assets/_fullsize"
  output: "img/generated"
  markup: "picture"
  presets:
      default:
          ppi: [1, 2, 3]
          source_desktop:
              media: "(min-width: 640px)"
              width: 500
          source_tablet:
              media: "(min-width: 480px)"
              width: 300
          source_mobile:
              media: "(min-width: 100px)"
              width: 400
          source_default:
              media:"(min-width: 40em)"
              width: "500"