# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: edward essing - art
email: edwardessing@gmail.com
description: 'edward essing - art'
baseurl: ''
url: 'http://edwardessing.com' # the base hostname & protocol for your site

plugins:
  - jekyll-sitemap

social:
  name: Edward Essing
  links:
    - https://instagram.com/edwardessing/

# Build settings
markdown: kramdown

# Server Config options
livereload: true     # You no longer need to include --livereload:
                     # jekyll serve -L
reload_port: 5678    # If you don't want to use the default port

# Sass
sass:
  style: compressed

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      categories: ''
      tags: []
      featured-image: ''
  - scope:
      path: ''
      type: pages
    values:
      layout: page
      featured-image: ''
  - scope:
      path: ''
      type: galleries
    values:
      layout: gallery
      tags: []
      featured-image: ''
      homepage-thumbnail: ''
  - scope:
      path: ''
      type: notes
    values:
      layout: note
      tags: []
      featured-image: ''
      homepage-thumbnail: ''

show_excerpts: true

# Collections
collections:
  galleries:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /:collection/:path/

autopages:
  enabled: false

permalink: pretty

exclude: [README.md, bower.json]